### PR TITLE
Many, many updates

### PR DESCRIPTION
**Pull request by Chuck5ta**
Many updates by many authors:
-- cala
-- cyberium
-- DDuarte
-- evil-at-wow
-- Grz3s
-- jeeron-- jpiolho
-- Kelzior
-- Killyana
-- Muehe
-- nekoi
-- neotmiren
-- Scotty0100
-- stfx
-- thetrueanimal
-- Tobschinski
-- Xfurry
-- zingzah

-- TrinityCore
-- UDB
-- YTDB

### CODE REVIEW

**Comment by Kittnz** [comment]
You are missing a few authors there.

**Comment by MadMaxMangos** [comment]
Any names you think can be added? I'll let chuck know there are some missing.

**Comment by Kittnz** [comment]
It's in the SQL itself so not really that a big of an issue it seems, but Killyana is not mentioned here.

**Comment by Kittnz** [comment]
It seems several db update from TC can be imported here, specially the world event ones.

**Comment by billy1arm** [comment]
@Kittnz - please feel free to add any think are missing and thanks for pointing out the authors in the sql

**Comment by Kittnz** [comment]
You guys use IRC?

**Comment by MadMaxMangos** [comment]
https://www.getmangos.eu/chat_irc.php

You'd have to arrange with @billy1arm when to meet him on there to chat.

**Comment by billy1arm** [comment]
@Kittnz - feel free to contact me on antz@getmangos.eu and we can arrange to chat more

**Pull request merged**
